### PR TITLE
WIP - Build systems in Docker on WSL

### PR DESCRIPTION
**Pull request by tmecklem**
This PR adds WSL OS type support to the build runner detection so that it knows to use Docker, and refactors WSL-specific code into `Nerves.Utils.WSL`

### CODE REVIEW

**Comment by fhunleth** [comment]
@tmecklem Where does this PR stand? It has conflicts, but are there any parts of it that we should consider merging?

**Comment by fhunleth** [comment]
@jmerriweather Thanks - please PR anything that you'd like from this. It makes me happy that Nerves Windows support is getting attention. Also, renaming `is_wsl?` is definitely appreciated - as would any PR that improves our conformance with the current Elixir naming guidelines. I'll leave this PR open until I hear from you that it's safe to close and delete the branch.

**Comment by GregMefford** [comment]
I know this PR is super old at this point, but wanted to mention that I learned today while working on #425 that WSL 2 now supports running Docker in WSL with a real Linux kernel. That could open up some new possibilities for building Nerves systems on Windows, as well as opening a path for standardizing how we do compiling in Nerves across all platforms, based on Docker.

https://devblogs.microsoft.com/commandline/announcing-wsl-2/

I haven't gotten WSL 2 set up yet, but it seems like at some point soon-ish, it should be out of tech preview and generally available for people to use if they want to develop with Nerves on Windows.

**Comment by fhunleth** [comment]
I'm closing this since I think that even though this wasn't merged, it served a really good purpose in driving Windows-related updates into Nerves.

**Pull request closed without merging**
