### PR TITLE
Add 9P path \\wsl$ for mix firmware.burn inside WSL on Windows 10 Version 1903

### PR DESCRIPTION
**Pull request by nabinno**
This PR will also enable `mix firmware.burn` for 1903 users 😊

**Reproduction:** Run `mix firmware.burn` inside WSL on Windows 10 Version 1903.
```
$ mix firmware.burn
** (Mix) Could not auto detect your SD card
```

**Reason:** With the introduction of 9P server, each distro's files can be accessed from `\\wsl$\{distro name}\` path.
```sh
$ wslpath -w -a .     
\\wsl$\Ubuntu-18.04\home\nab\hello_nerves\  
```
Cf. https://devblogs.microsoft.com/commandline/whats-new-for-wsl-in-windows-10-version-1903/

### CODE REVIEW

**Comment by GregMefford** [comment]
Thanks a lot fo taking the time to contribute this, and especially for the link to the details! I'd like to get to a better place with Windows support, but it's tough when the core team doesn't really use Windows regularly for Nerves development.

I'm planning to dig into this over the weekend and make sure I can get it working / understand what's going on. 😁

**Comment by GregMefford** [comment]
One question I have that's related to this change but not directly about the change: should this also work with UNC paths more generally, like `\\servername\path\to\some\directory\`? It seems like Microsoft is just treating `wsl$` as a special UNC server name that happens to run inside the Linux distro instance, so I'm curious, from a Nerves perspective, if we should support targeting _any_ UNC path, or just these special `wsl$` ones.

**Comment by GregMefford** [comment]
It looks like getting 1903 installed is an all-day event for some reason? 🙃 
So... I'm working on it, but it's going to be tomorrow before I can try anything probably.

**Comment by nabinno** [comment]
@GregMefford 
> One question I have that's related to this change but not directly about the change: should this also work with UNC paths more generally, like \\servername\path\to\some\directory\?

Yes, I was careless🙏 Certainly, there is a case where UNC path is used on WSL: By mounting the network location on the WSL and converting the WSL path to a Windows path with the `wslpath` command, I could obtain a UNC path.

```
$ sudo mkdir /mnt/share
$ sudo mount -t drvfs '\\OTHERMACHINE\Users\nab' /mnt/share
$ wslpath -w -a /mnt/share
\\OTHERMACHINE\Users\nab
```

**Comment by nabinno** [comment]
Hi! WSL 2 has released 😅

I got the same error when I ran `mix firmware.burn` with WSL 2 and will add a fixed commit!

**Reproduction:** Run `mix firmware.burn` inside WSL 2 on Windows 10 Version 1903 OS build 18917.1000.
```
$ MIX_TARGET=rpi0 mix firmware.burn
** (Mix) Could not auto detect your SD card
```

**Reason:** `osrelease` differs between WSL 1 and WSL 2.
```sh
# WSL 1
$ cat /proc/sys/kernel/osrelease
4.4.0-18917-Microsoft

# WSL 2
$ cat /proc/sys/kernel/osrelease
4.19.43-microsoft-standard
```

Cf. https://devblogs.microsoft.com/commandline/wsl-2-is-now-available-in-windows-insiders/

**Comment by fhunleth** [comment]
@GregMefford and @nabinno - Sorry I haven't been paying attention to this issue. Where do things stand?

**Comment by GregMefford** [comment]
I'm working on confirming this fix today. Thanks so much for your patience @nabinno! 😅

**Comment by GregMefford** [comment]
I pushed some updated commits to get this PR rebased onto current master, and I'm giving it a try locally to make sure things are working.

**Comment by fhunleth** [comment]
Thanks @nabinno and @GregMefford for all of the work on this PR!

**Pull request merged**
