### PR TITLE
Add NERVES_DATA_DIR to specify global nerves data location

### PR DESCRIPTION
**Pull request by mobileoverlord**
This also adds support for XDG_DATA_HOME as described in  https://github.com/elixir-lang/elixir/pull/8933

This is going to require some documentation but I wanted to start the discussion on the variable name. Considering that the subcomponents of this could be set via `NERVES_DL_DIR` and `NERVES_ARTIFACTS_DIR` I chose to fix the existing but broken `data_dir/0` function and call it `NERVES_DATA_DIR`.

### CODE REVIEW

**Comment by mobileoverlord** [comment]
Fixes https://github.com/nerves-project/nerves/issues/386

**Comment by fhunleth** [comment]
@mobileoverlord What do you think about this line in the XDG spec:

>$XDG_DATA_HOME defines the base directory relative to which user specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used. 

That reads to me that defaulting to `~/.nerves` if `$XDG_DATA_HOME` is not set is not the intended behavior.

**Comment by mobileoverlord** [comment]
If we change the default from `~/.nerves` to `$HOME/.local/share` it would happen for everyone, which should be okay. I wonder if there is another `XDG` variable that is guaranteed to be set and could be used to determine which default to choose?

**Comment by fhunleth** [comment]
Yes, that would be confusing. It sounds like completely following XDG is a Nerves 2.0 thing.

**Pull request merged**
