### PR TITLE
Remove `make clean` from `nerves.system.shell` and refresh System docs

### PR DESCRIPTION
**Pull request by GregMefford**
* `mix nerves.system.shell` does not run `make clean` automatically (see #161)
* Better error-checking and error messages in a few cases that I hadn't hit until now (like `mix deps.get` not having been run yet)
* Updated System docs to be current and also cover `nerves.system.shell`

**Specific feedback requested:**

I'm not 100% clear on whether I got the `make linux-savedefconfig` and `make busybox-savedefconfig` documentation right, since that's not something I've done very often. Let me know if it's not right. I feel like it might have been automated so you don't have to manually copy the files anymore, but I wasn't sure.

### CODE REVIEW

**Comment by ConnorRigby** [comment]
Im not sure if it is fixed yet, but as of feb 2016, (that was the last time i tried) `make linux-savedefconfig` and `make busybox-savedefconfig` did not work for me as intended. (or i read the docs wrong)

**Comment by fhunleth** [comment]
Regarding the `make *-savdefconfig` commands, the expected Buildroot behavior is to keep the resulting `defconfig` files in the `build` directories. It's wrong to copy them back to the source since you may have instructed Buildroot to concatenate several defconfig fragments together and it won't know how to split them up again. I also believe that I saw an discussion that the `make savedefconfig` implementation in Buildroot that would save back to the original `defconfig` file was not desired.

All of this makes things more manual, but since my workflow is to meticulously check the defconfig deltas whenever I copy the new defconfigs over, I'm not sure that it costs me any time.

**Comment by ConnorRigby** [comment]
Ah ok. I do it all manually also. But last time i tried to use those commands (specifically busybox) - it actually failed due to a missing file and i haven't tried it since. The docs look good to me tho @GregMefford

**Comment by mobileoverlord** [comment]
Looks good to me. Thanks @GregMefford

**Pull request merged**
