### PR TITLE
Nerves connecting

### PR DESCRIPTION
**Pull request by deanchouinard**

### CODE REVIEW

**Comment by fhunleth** [comment]
@deanchouinard Could you rebase this on `master` and squash the commits into one?

**Comment by fhunleth** [comment]
@deanchouinard I'm going to rebase your PR and fix the conflict so that we can get this change into the release.

**Comment by fhunleth** [comment]
I fixed the conflict and squashed: 69cad889ae7f809389467e12c807b3076de5e9d2. Thanks!

**Comment by deanchouinard** [comment]
Thank you for straightening out the commits.

**Pull request closed without merging**
