### PR TITLE
Added example for switching targets

### PR DESCRIPTION
**Pull request by Pacodastre**
The title is pretty straight forward.

One thing to note, is that the `Note` part of the example repeats what has been said just above. I'm not sure this is great.

Feedbacks are welcome.

### CODE REVIEW

**Comment by fhunleth** [comment]
I think this is a good update to the docs. @mobileoverlord - did  you see it?

**Comment by mobileoverlord** [comment]
Yup, sorry I was waiting to re read through. Looks good :bowtie:

**Comment by GregMefford** [comment]
Thank you, @pacodastre!

**Comment by Pacodastre** [comment]
No problem. Hopefully, there'll be more to come :-)

**Pull request merged**
