### PR TITLE
Enhanced Console Messages

### PR DESCRIPTION
**Pull request by mobileoverlord**
This cleans up and aligns console messages as well as adding nerves.info. This will gather information about the env withoug invoking the env compilers

### CODE REVIEW

**Comment by mobileoverlord** [comment]
> Maybe add a warning message when --target fails. Also, update the docs for this change.
This was changed in https://github.com/nerves-project/nerves/pull/76

> There's a lot of different shell output calls that vary between using shell_info + Mix.shell.info + IO.write. Review and standardize if possible.
These have been consolidated into a module in nerves_bootstrap

> We're using two different conventions for changing ANSI colors. Pick one. [IO.ANSI.inverse, IO.ANSI.red, "|#{loc}| #{text}", IO.ANSI.reset] vs. as you did in PR #76 with the atom convention.
These have been consolidated

**Comment by electricshaman** [comment]
🙌🏻

**Comment by mobileoverlord** [comment]
This now requires bootstrap and nerves to lock step, going to make the new bootstrap 0.3 and have nerves 0.5 require at least it

**Comment by GregMefford** [comment]
Looks good!

**Pull request merged**
